---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

```{r cars}
library(haven)
library(zoo)
library(survival)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(gtsummary)
library(survRM2)
library(MatchIt)
library(cobalt)
library(knitr)
library(kableExtra)
library(coxme)
library(survminer)
library(nlme)
```


```{r cars}
#load data
tx_data = read_sas("tx_ki.sas7bdat")
donor_data = read_sas("donor_deceased.sas7bdat")
```



```{r pressure, echo=FALSE}
#reduce to SKTs and enblocs, specify study period
type_filt = c("101", "102", "103")
enbloc = tx_data[tx_data$REC_TX_PROCEDURE_TY %in% type_filt, ]
new_policy = enbloc[(enbloc$REC_TX_DT >= "2020-12-15") & (enbloc$REC_TX_DT <= "2021-12-31"),]
```

```{r}
#indicators for graft failure and death, event defined as at least one of these occuring
new_policy = new_policy %>%
            mutate(death_ind = ifelse(is.na(TFL_DEATH_DT), 0, 1), 
                   graft_ind = ifelse(is.na(TFL_GRAFT_DT), 0, 1), 
                   event = pmax(death_ind , graft_ind))
```

```{r}
#time to graft failure, death, or censoring
new_policy = new_policy %>% mutate(death_time = difftime(new_policy$TFL_DEATH_DT,new_policy$REC_TX_DT, units = "days"),
                      graft_time = difftime(new_policy$TFL_GRAFT_DT,new_policy$REC_TX_DT, units = "days"),
                      censored_time = difftime(new_policy$TFL_LAFUDATE, new_policy$REC_TX_DT, units = "days"))

new_policy = new_policy %>% mutate(death_time = replace(new_policy$death_time, is.na(new_policy$death_time), 1000),
                      graft_time = replace(new_policy$graft_time, is.na(new_policy$graft_time), 1000))
                      
new_policy = new_policy %>% mutate (time = pmin(new_policy$death_time, new_policy$graft_time, new_policy$censored_time))



```



```{r}
#function for calculating kdri
kdri = function(age, age18_ind, age50_ind, height, weight, weight_ind, ethnicity, hypertension, diabetes, cod, creatine, creatine_ind, hcv, dcd){
  x_beta = 0.0128*(age-40)-(0.0194*(age-18)*(age18_ind))+(0.0107*(age-50)*(age50_ind))-0.0464*(height-170)/10-0.0199*((weight-80)/5)*weight_ind+0.179*ethnicity+0.126*hypertension+0.13*diabetes+0.0881*cod+0.22*(creatine-1)-0.209*(creatine-1)*(creatine_ind)+0.24*hcv+0.133*dcd
  kdri = (exp(x_beta))/1.33586831546044 
}


```


```{r}
#means for missing value imputation
mean_height = mean(new_policy$DON_HGT_CM, na.rm = TRUE) 
mean_weight = mean(new_policy$DON_WGT_KG, na.rm = TRUE) 
mean_creat = mean(new_policy$DON_CREAT, na.rm = TRUE) 

#varables for kdri and skt vs enbloc
new_policy <- new_policy %>%
  mutate(
    age18_ind = ifelse(DON_AGE < 18, 1, 0),
    age50_ind = ifelse(DON_AGE > 50, 1, 0),
    DON_HGT_CM = ifelse(is.na(DON_HGT_CM), mean(DON_HGT_CM, na.rm = TRUE), DON_HGT_CM),
    DON_WGT_KG = ifelse(is.na(DON_WGT_KG), mean(DON_WGT_KG, na.rm = TRUE), DON_WGT_KG),
    weight_ind = ifelse(DON_WGT_KG < 80, 1, 0),
    ethnicity = ifelse(DON_RACE == 16, 1, 0),
    diabetes = ifelse(DON_HIST_DIAB %in% c(2, 3, 4, 5), 1, 0),
    hypertension = ifelse(DON_HIST_HYPERTEN %in% c(2, 3, 4, 5), 1, 0),
    cod = ifelse(is.na(DON_CAD_DON_COD) | DON_CAD_DON_COD != 2, 0, 1),
    DON_CREAT = ifelse(is.na(DON_CREAT), mean(DON_CREAT, na.rm = TRUE), DON_CREAT),
    DON_HIGH_CREAT = ifelse(is.na(DON_HIGH_CREAT), 0, DON_HIGH_CREAT),
    hcv = ifelse(DON_ANTI_HCV == 'P', 1, 0),
    skt = as.numeric(REC_TX_PROCEDURE_TY %in% c("101", "102")),
    enbloc = as.numeric(REC_TX_PROCEDURE_TY == "103")
  )

```

```{r}
#merging donor deceased dataset to access dcd information
seq_data = merge(new_policy, donor_data, by="DONOR_ID", all.x=TRUE)
#creating dcd indicator based on whether the patient had a date for support withdrawal for dcd
seq_data$dcd = ifelse(is.na(seq_data$DON_DCD_SUPPORT_WITHDRAW_DT), 0, 1)
```

```{r}
#creating kdri variable using function from earlier
seq_data$kdri = kdri(age=seq_data$DON_AGE.x, age18_ind = seq_data$age18_ind, age50_ind = seq_data$age50_ind, height=seq_data$DON_HGT_CM.x, weight=seq_data$DON_WGT_KG.x, weight_ind=seq_data$weight_ind, ethnicity=seq_data$ethnicity, hypertension=seq_data$hypertension, diabetes=seq_data$diabetes, cod=seq_data$cod, creatine=seq_data$DON_CREAT.x, creatine_ind=seq_data$DON_HIGH_CREAT.x, hcv=seq_data$hcv, dcd=seq_data$dcd)

```



```{r}

#coding sequences (using kdpi mapping table)
seq_data$seq = ifelse((seq_data$REC_TX_PROCEDURE_TY %in% c(101, 102) & seq_data$kdri <= 0.73652249238699), 
  1, ifelse((seq_data$REC_TX_PROCEDURE_TY %in% c(101, 102) & seq_data$kdri > 0.73652249238699 & seq_data$kdri <= 0.86220561525508),
  2, ifelse((seq_data$REC_TX_PROCEDURE_TY %in% c(101, 102) & seq_data$kdri > 0.86220561525508 & seq_data$kdri < 1.48742806263682),
  3, ifelse(seq_data$REC_TX_PROCEDURE_TY == 103, 0, 4))))

#variables for input into epts function and table 1
seq_data = seq_data %>% 
  mutate(dialysis_duration = ifelse(is.na(seq_data$REC_DIAL_DT) == FALSE, (seq_data$REC_TX_DT-seq_data$REC_DIAL_DT)/365, 0),
  no_dial = ifelse(is.na(seq_data$REC_DIAL_DT), 1, 0),
  type = ifelse(seq_data$seq == 0, 'En Bloc', ifelse(seq_data$seq == 1, 'Sequence A SKT', ifelse(seq_data$seq == 2, 'Sequence B SKT', ifelse(seq_data$seq == 3, 'Sequence C SKT', 'Sequence D SKT')))),
  rec_diabetes = ifelse(seq_data$CAN_DIAB_TY %in% c(1, 998), 0, 1),
  rec_htn = ifelse(seq_data$CAN_DRUG_TREAT_HYPERTEN == 'Y', 1, 0),
  DON_CAD_DON_COD.x = ifelse(is.na(seq_data$DON_CAD_DON_COD.x), "997", seq_data$DON_CAD_DON_COD.x)) 

seq_data = seq_data %>%
  mutate(don_death = ifelse(seq_data$DON_CAD_DON_COD.x == 1, "Anoxia", ifelse(seq_data$DON_CAD_DON_COD.x == 2, "Cerebrovascular / Stroke", ifelse(seq_data$DON_CAD_DON_COD.x == 3, "Head Trauma", "Other"))),
  enbloc_under1 = ifelse((seq_data$enbloc == 1) & (seq_data$DON_AGE.x < 1), 1, 0),
  enbloc_over1 = ifelse((seq_data$enbloc == 1) & (seq_data$DON_AGE.x >= 1), 1, 0))



```

```{r}
#epts function
raw_epts = function(rec_age, rec_diabetes, prev_trans, dialysis_time, never_dialyzed){
  (0.047*pmax((rec_age-25), 0)) - (0.015*rec_diabetes*pmax(rec_age-25, 0)) + (0.398*prev_trans - 0.237*rec_diabetes*prev_trans) + (0.315*log(dialysis_time+1)) - (0.099*rec_diabetes*log(dialysis_time+1)) + (0.13*never_dialyzed) - (0.348*rec_diabetes*never_dialyzed) + (1.262*rec_diabetes)
}


seq_data$raw_epts = raw_epts(rec_age=seq_data$REC_AGE_AT_TX, rec_diabetes = seq_data$rec_diabetes, prev_trans = seq_data$CAN_PREV_TX, dialysis_time = seq_data$dialysis_duration, never_dialyzed = seq_data$no_dial)



```


```{r}
ranges = c(0, 0.01018270481040, 0.22506076343394, 0.40495482546201, 0.52668514715948, 0.62047375671598, 0.71217182144415, 0.79382272416153 , 0.86729842573580, 0.93498357289528, 0.99597348476971, 1.05786789869952, 1.11693566050650, 1.17275499673116, 1.22631279945243, 1.27416204029441,  1.32193032901076, 1.36766159145183, 1.41251129363450, 1.45407460643395, 1.49615263518138, 1.53510169752232, 1.57194455852156, 1.60810335386721, 1.64129842573580, 1.67214899950875, 1.70203901437372 , 1.73137577002053, 1.75916837782341, 1.78568035592060, 1.81224093086927, 1.83669048683774,  1.86111365374575, 1.88477236354207, 1.90643999445176, 1.92833430315357, 1.95061672659645, 1.97180487135921, 1.99204930532186, 2.01394354154568, 2.03469979247238, 2.05470362236001, 2.07314715947981, 2.09049418206708, 2.10819164955510, 2.12593159093198, 2.14428747433265, 2.16003492859569, 2.17748138612887, 2.19422578065599, 2.21008350444901, 2.22681724845996, 2.24248665297741, 2.25866298097784, 2.27414579055441, 2.28965674569174, 2.30496646132786, 2.32064887063655, 2.33546300210562, 2.35058110882957,  2.36495682765023, 2.37956850034990, 2.39331000806028, 2.40794239525345, 2.42332922655715, 2.43824748244487, 2.45301341435239, 2.46883709787817, 2.48377825234404, 2.49765884856653, 2.51217225971966, 2.52701858141310, 2.54203650226714, 2.55860095824778, 2.57424912221794, 2.59040383299110, 2.60722141715292, 2.62498083504449, 2.64263627984686, 2.65921246229145, 2.67635098661546, 2.69390568835368, 2.71193480771995, 2.73135215563315, 2.75130096122788, 2.77165233216905, 2.79135338420568, 2.81295668156198, 2.83484476578948, 2.85613932665133, 2.87925967560719, 2.90216882375627, 2.92553421191676, 2.95158539985534, 2.97980484197221, 3.01023840891310, 3.03924343753914, 3.07520998352032, 3.11767479308614, 3.17001351953696, 3.25028785715597, 999999999)


assigned_values = seq(0,100)

seq_data$epts = as.numeric(cut(seq_data$raw_epts, breaks = ranges, labels = assigned_values, right = FALSE))
save(seq_data, file = "seq_data.Rdata")
```

```{r}
#different datasets for en blocs < 1 and >= 1 compared to each sequence

seq_a_data_under = seq_data[(seq_data$seq == 1) | (seq_data$enbloc_under1 == 1),]
seq_b_data_under = seq_data[(seq_data$seq == 2) | (seq_data$enbloc_under1 == 1),]
seq_c_data_under = seq_data[(seq_data$seq == 3) | (seq_data$enbloc_under1 == 1),]
seq_d_data_under = seq_data[(seq_data$seq == 4) | (seq_data$enbloc_under1 == 1),]

seq_a_data_over = seq_data[(seq_data$seq == 1) | (seq_data$enbloc_over1 == 1),]
seq_b_data_over = seq_data[(seq_data$seq == 2) | (seq_data$enbloc_over1 == 1),]
seq_c_data_over = seq_data[(seq_data$seq == 3) | (seq_data$enbloc_over1 == 1),]
seq_d_data_over = seq_data[(seq_data$seq == 4) | (seq_data$enbloc_over1 == 1),]

save(seq_a_data_under, file = "seq_a_data_under.Rdata")
save(seq_a_data_over, file = "seq_a_data_over.Rdata")
```

```{r}
#rmst for enbloc vs SKTs

rmst_seq_a_under = rmst2(time=seq_a_data_under$time, status=seq_a_data_under$event, arm=seq_a_data_under$enbloc_under1, tau=365)
rmst_seq_b_under = rmst2(time=seq_b_data_under$time, status=seq_b_data_under$event, arm=seq_b_data_under$enbloc_under1, tau=365)
rmst_seq_c_under = rmst2(time=seq_c_data_under$time, status=seq_c_data_under$event, arm=seq_c_data_under$enbloc_under1, tau=365)
rmst_seq_d_under = rmst2(time=seq_d_data_under$time, status=seq_d_data_under$event, arm=seq_d_data_under$enbloc_under1, tau=365)

rmst_seq_a_over = rmst2(time=seq_a_data_over$time, status=seq_a_data_over$event, arm=seq_a_data_over$enbloc_over1, tau=365)
rmst_seq_b_over = rmst2(time=seq_b_data_over$time, status=seq_b_data_over$event, arm=seq_b_data_over$enbloc_over1, tau=365)
rmst_seq_c_over = rmst2(time=seq_c_data_over$time, status=seq_c_data_over$event, arm=seq_c_data_over$enbloc_over1, tau=365)
rmst_seq_d_over = rmst2(time=seq_d_data_over$time, status=seq_d_data_over$event, arm=seq_d_data_over$enbloc_over1, tau=365)

```




```{r}
#restructure data for hazard ratio calculation
#en blocs < 1 compared to sequence a skt


condition = seq_a_data_under$time > 90
duplicated_rows = seq_a_data_under[condition, ]

seq_a_data_under$time_start = pmin(0, seq_a_data_under$time)
seq_a_data_under$time_stop = ifelse(seq_a_data_under$time==0, 0.00001, pmin(seq_a_data_under$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

a_data_under = rbind(seq_a_data_under, duplicated_rows)
a_data_under = a_data_under[order(a_data_under$DONOR_ID), ]
a_data_under$time_start = as.numeric(a_data_under$time_start, units = "days")
a_data_under$time_stop = as.numeric(a_data_under$time_stop, units = "days")

a_data_under$en_bloc_pre_90 = ifelse(a_data_under$time_start == 0 & a_data_under$enbloc == 1, 1, 0)
a_data_under$en_bloc_post_90 = ifelse(a_data_under$time_start == 90 & a_data_under$enbloc == 1, 1, 0)


```

```{r}
#restructure data for hazard ratio calculation
#en blocs >= 1 compared to sequence a skts


condition = seq_a_data_over$time > 90
duplicated_rows = seq_a_data_over[condition, ]

seq_a_data_over$time_start = pmin(0, seq_a_data_over$time)
seq_a_data_over$time_stop = ifelse(seq_a_data_over$time==0, 0.00001, pmin(seq_a_data_over$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

a_data_over = rbind(seq_a_data_over, duplicated_rows)
a_data_over = a_data_over[order(a_data_over$DONOR_ID), ]
a_data_over$time_start = as.numeric(a_data_over$time_start, units = "days")
a_data_over$time_stop = as.numeric(a_data_over$time_stop, units = "days")

a_data_over$en_bloc_pre_90 = ifelse(a_data_over$time_start == 0 & a_data_over$enbloc == 1, 1, 0)
a_data_over$en_bloc_post_90 = ifelse(a_data_over$time_start == 90 & a_data_over$enbloc == 1, 1, 0)

```

```{r}
#restructure data for alternate hazard ratio method
#en blocs < 1 compared to sequence b skts


condition = seq_b_data_under$time > 90
duplicated_rows = seq_b_data_under[condition, ]

seq_b_data_under$time_start = pmin(0, seq_b_data_under$time)
seq_b_data_under$time_stop = ifelse(seq_b_data_under$time==0, 0.00001, pmin(seq_b_data_under$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

b_data_under = rbind(seq_b_data_under, duplicated_rows)
b_data_under = b_data_under[order(b_data_under$DONOR_ID), ]
b_data_under$time_start = as.numeric(b_data_under$time_start, units = "days")
b_data_under$time_stop = as.numeric(b_data_under$time_stop, units = "days")

b_data_under$en_bloc_pre_90 = ifelse(b_data_under$time_start == 0 & b_data_under$enbloc == 1, 1, 0)
b_data_under$en_bloc_post_90 = ifelse(b_data_under$time_start == 90 & b_data_under$enbloc == 1, 1, 0)

```

```{r}
#restructure data for hazard ratio calculation
#en blocs >= 1 compared to sequence b skts


condition = seq_b_data_over$time > 90
duplicated_rows = seq_b_data_over[condition, ]

seq_b_data_over$time_start = pmin(0, seq_b_data_over$time)
seq_b_data_over$time_stop = ifelse(seq_b_data_over$time==0, 0.00001, pmin(seq_b_data_over$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

b_data_over = rbind(seq_b_data_over, duplicated_rows)
b_data_over = b_data_over[order(b_data_over$DONOR_ID), ]
b_data_over$time_start = as.numeric(b_data_over$time_start, units = "days")
b_data_over$time_stop = as.numeric(b_data_over$time_stop, units = "days")

b_data_over$en_bloc_pre_90 = ifelse(b_data_over$time_start == 0 & b_data_over$enbloc == 1, 1, 0)
b_data_over$en_bloc_post_90 = ifelse(b_data_over$time_start == 90 & b_data_over$enbloc == 1, 1, 0)

```

```{r}
#restructure data for hazard ratio calculation
#en blocs < 1 compared to sequence c skts


condition = seq_c_data_under$time > 90
duplicated_rows = seq_c_data_under[condition, ]

seq_c_data_under$time_start = pmin(0, seq_c_data_under$time)
seq_c_data_under$time_stop = ifelse(seq_c_data_under$time==0, 0.00001, pmin(seq_c_data_under$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

c_data_under = rbind(seq_c_data_under, duplicated_rows)
c_data_under = c_data_under[order(c_data_under$DONOR_ID), ]
c_data_under$time_start = as.numeric(c_data_under$time_start, units = "days")
c_data_under$time_stop = as.numeric(c_data_under$time_stop, units = "days")

c_data_under$en_bloc_pre_90 = ifelse(c_data_under$time_start == 0 & c_data_under$enbloc == 1, 1, 0)
c_data_under$en_bloc_post_90 = ifelse(c_data_under$time_start == 90 & c_data_under$enbloc == 1, 1, 0)

```

```{r}
#restructure data for hazard ratio calculation
#en blocs >= 1 compared to sequence c skts


condition = seq_c_data_over$time > 90
duplicated_rows = seq_c_data_over[condition, ]

seq_c_data_over$time_start = pmin(0, seq_c_data_over$time)
seq_c_data_over$time_stop = ifelse(seq_c_data_over$time==0, 0.00001, pmin(seq_c_data_over$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

c_data_over = rbind(seq_c_data_over, duplicated_rows)
c_data_over = c_data_over[order(c_data_over$DONOR_ID), ]
c_data_over$time_start = as.numeric(c_data_over$time_start, units = "days")
c_data_over$time_stop = as.numeric(c_data_over$time_stop, units = "days")

c_data_over$en_bloc_pre_90 = ifelse(c_data_over$time_start == 0 & c_data_over$enbloc == 1, 1, 0)
c_data_over$en_bloc_post_90 = ifelse(c_data_over$time_start == 90 & c_data_over$enbloc == 1, 1, 0)

```

```{r}
#restructure data for hazard ratio calculation
#en blocs < 1 compared to sequence d skts


condition = seq_d_data_under$time > 90
duplicated_rows = seq_d_data_under[condition, ]

seq_d_data_under$time_start = pmin(0, seq_d_data_under$time)
seq_d_data_under$time_stop = ifelse(seq_d_data_under$time==0, 0.00001, pmin(seq_d_data_under$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

d_data_under = rbind(seq_d_data_under, duplicated_rows)
d_data_under = d_data_under[order(d_data_under$DONOR_ID), ]
d_data_under$time_start = as.numeric(d_data_under$time_start, units = "days")
d_data_under$time_stop = as.numeric(d_data_under$time_stop, units = "days")

d_data_under$en_bloc_pre_90 = ifelse(d_data_under$time_start == 0 & d_data_under$enbloc == 1, 1, 0)
d_data_under$en_bloc_post_90 = ifelse(d_data_under$time_start == 90 & d_data_under$enbloc == 1, 1, 0)

```

```{r}
#restructure data for hazard ratio calculation
#en blocs >= 1 compared to sequence d skts


condition = seq_d_data_over$time > 90
duplicated_rows = seq_d_data_over[condition, ]

seq_d_data_over$time_start = pmin(0, seq_d_data_over$time)
seq_d_data_over$time_stop = ifelse(seq_d_data_over$time==0, 0.00001, pmin(seq_d_data_over$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

d_data_over = rbind(seq_d_data_over, duplicated_rows)
d_data_over = d_data_over[order(d_data_over$DONOR_ID), ]
d_data_over$time_start = as.numeric(d_data_over$time_start, units = "days")
d_data_over$time_stop = as.numeric(d_data_over$time_stop, units = "days")

d_data_over$en_bloc_pre_90 = ifelse(d_data_over$time_start == 0 & d_data_over$enbloc == 1, 1, 0)
d_data_over$en_bloc_post_90 = ifelse(d_data_over$time_start == 90 & d_data_over$enbloc == 1, 1, 0)

```

```{r}
#propensity score matching with en blocs < 1

match_obj = matchit(enbloc_under1 ~ REC_AGE_AT_TX + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + dialysis_duration*REC_AGE_AT_TX, data = seq_a_data_under, method = "nearest", distance ="glm",
  ratio = 1,
  replace = FALSE)
match_data_under = match.data(match_obj)


summary(match_obj)
save(match_data_under, file = "match_data_under.Rdata")
```

```{r}
#propensity score matching with en blocs >= 1

match_obj = matchit(enbloc_over1 ~ REC_AGE_AT_TX + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + dialysis_duration*rec_diabetes, data = seq_a_data_over, method = "nearest", distance ="glm",
  ratio = 1,
  replace = FALSE)
match_data_over = match.data(match_obj)


summary(match_obj)
save(match_data_over, file = "match_data_over.Rdata")
```


```{r}
#restructure data for hazard ratio calculation
#en blocs < 1 compared to propensity score matched sequence a skts
condition = match_data_under$time > 90
duplicated_rows = match_data_under[condition, ]

match_data_under$time_start = pmin(0, match_data_under$time)
match_data_under$time_stop = ifelse(match_data_under$time==0, 0.00001, pmin(match_data_under$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

matched_data_under = rbind(match_data_under, duplicated_rows)
matched_data_under = matched_data_under[order(matched_data_under$DONOR_ID), ]
matched_data_under$time_start = as.numeric(matched_data_under$time_start, units = "days")
matched_data_under$time_stop = as.numeric(matched_data_under$time_stop, units = "days")

matched_data_under$en_bloc_pre_90 = ifelse(matched_data_under$time_start == 0 & matched_data_under$enbloc == 1, 1, 0)
matched_data_under$en_bloc_post_90 = ifelse(matched_data_under$time_start == 90 & matched_data_under$enbloc == 1, 1, 0)


```

```{r}
#restructure data for hazard ratio calculation
#en blocs >= 1 compared to propensity score matched sequence a skts

condition = match_data_over$time > 90
duplicated_rows = match_data_over[condition, ]

match_data_over$time_start = pmin(0, match_data_over$time)
match_data_over$time_stop = ifelse(match_data_over$time==0, 0.00001, pmin(match_data_over$time, 90))
duplicated_rows$time_start = 90
duplicated_rows$time_stop = duplicated_rows$time

matched_data_over = rbind(match_data_over, duplicated_rows)
matched_data_over = matched_data_over[order(matched_data_over$DONOR_ID), ]
matched_data_over$time_start = as.numeric(matched_data_over$time_start, units = "days")
matched_data_over$time_stop = as.numeric(matched_data_over$time_stop, units = "days")

matched_data_over$en_bloc_pre_90 = ifelse(matched_data_over$time_start == 0 & matched_data_over$enbloc == 1, 1, 0)
matched_data_over$en_bloc_post_90 = ifelse(matched_data_over$time_start == 90 & matched_data_over$enbloc == 1, 1, 0)

```


```{r}
#unadjusted models vs en blocs < 1
a_cox_model_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=a_data_under)
b_cox_model_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=b_data_under)
c_cox_model_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=c_data_under)
d_cox_model_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=d_data_under)

#unadjusted models vs en blocs >= 1
a_cox_model_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=a_data_over)
b_cox_model_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=b_data_over)
c_cox_model_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=c_data_over)
d_cox_model_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data=d_data_over)

#adjusted models vs en blocs < 1
a_cox_adjusted_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=a_data_under)
b_cox_adjusted_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=b_data_under)
c_cox_adjusted_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=c_data_under)
d_cox_adjusted_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=d_data_under)

#adjusted models vs en blocs >= 1
a_cox_adjusted_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=a_data_over)
b_cox_adjusted_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=b_data_over)
c_cox_adjusted_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=c_data_over)
d_cox_adjusted_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + REC_AGE_AT_TX  + dialysis_duration + no_dial + rec_diabetes + CAN_PREV_TX + (1|REC_CTR_CD), data=d_data_over)

#propensity score matched models
cox_matched_under = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data = matched_data_under)
cox_matched_over = coxme(Surv(time_start, time_stop, event) ~ en_bloc_pre_90 + en_bloc_post_90 + (1|REC_CTR_CD), data = matched_data_over)

```


```{r}
#mean survival time for matched SKTs
rmst_seq_a_match_under = rmst2(time=match_data_under$time, status=match_data_under$event, arm=match_data_under$enbloc_under1, tau=365)
rmst_seq_a_match_over = rmst2(time=match_data_over$time, status=match_data_over$event, arm=match_data_over$enbloc_over1, tau=365)

```

Pre-policy cohort
```{r pressure, echo=FALSE}
enbloc_filt = c("101", "102", "103")
enbloc = tx_data[tx_data$REC_TX_PROCEDURE_TY %in% enbloc_filt, ]
old_policy = enbloc[(enbloc$REC_TX_DT >= "2010-01-01") & (enbloc$REC_TX_DT < "2012-12-31"),]
```

```{r}
old_policy = old_policy %>%
            mutate(death_ind = ifelse(is.na(TFL_DEATH_DT), 0, 1), 
                   graft_ind = ifelse(is.na(TFL_GRAFT_DT), 0, 1), 
                   event = pmax(death_ind , graft_ind))

```

```{r}
#time to graft failure, death, or censoring
old_policy = old_policy %>% mutate(death_time = difftime(old_policy$TFL_DEATH_DT,old_policy$REC_TX_DT, units = "days"),
                      graft_time = difftime(old_policy$TFL_GRAFT_DT,old_policy$REC_TX_DT, units = "days"),
                      censored_time = difftime(old_policy$TFL_LAFUDATE, old_policy$REC_TX_DT, units = "days"))

old_policy = old_policy %>% mutate(death_time = replace(old_policy$death_time, is.na(old_policy$death_time), 10000),
                      graft_time = replace(old_policy$graft_time, is.na(old_policy$graft_time), 10000))
                      
old_policy$time = pmin(old_policy$death_time, old_policy$graft_time, old_policy$censored_time)



```

```{r}
#means for missing value imputation
mean_height = mean(old_policy$DON_HGT_CM, na.rm = TRUE) 
mean_weight = mean(old_policy$DON_WGT_KG, na.rm = TRUE) 
mean_creat = mean(old_policy$DON_CREAT, na.rm = TRUE) 

#varables for kdri and skt vs enbloc
old_policy <- old_policy %>%
  mutate(
    age18_ind = ifelse(DON_AGE < 18, 1, 0),
    age50_ind = ifelse(DON_AGE > 50, 1, 0),
    DON_HGT_CM = ifelse(is.na(DON_HGT_CM), mean(DON_HGT_CM, na.rm = TRUE), DON_HGT_CM),
    DON_WGT_KG = ifelse(is.na(DON_WGT_KG), mean(DON_WGT_KG, na.rm = TRUE), DON_WGT_KG),
    weight_ind = ifelse(DON_WGT_KG < 80, 1, 0),
    ethnicity = ifelse(DON_RACE == 16, 1, 0),
    diabetes = ifelse(DON_HIST_DIAB %in% c(2, 3, 4, 5), 1, 0),
    hypertension = ifelse(DON_HIST_HYPERTEN %in% c(2, 3, 4, 5), 1, 0),
    cod = ifelse(is.na(DON_CAD_DON_COD) | DON_CAD_DON_COD != 2, 0, 1),
    DON_CREAT = ifelse(is.na(DON_CREAT), mean(DON_CREAT, na.rm = TRUE), DON_CREAT),
    DON_HIGH_CREAT = ifelse(is.na(DON_HIGH_CREAT), 0, DON_HIGH_CREAT),
    hcv = ifelse(DON_ANTI_HCV == 'P', 1, 0),
    skt = as.numeric(REC_TX_PROCEDURE_TY %in% c("101", "102")),
    enbloc = as.numeric(REC_TX_PROCEDURE_TY == "103")
  )


```

```{r}
#merging donor deceased dataset to access dcd information
merged_old = merge(old_policy, donor_data, by="DONOR_ID", all.x=TRUE)
#creating dcd indicator based on whether the patient had a date for support withdrawal for dcd
merged_old$dcd = ifelse(is.na(merged_old$DON_DCD_SUPPORT_WITHDRAW_DT), 0, 1)
```

```{r}
#creating kdri variable using function from earlier
merged_old$kdri = kdri(age=merged_old$DON_AGE.x, age18_ind = merged_old$age18_ind, age50_ind = merged_old$age50_ind, height=merged_old$DON_HGT_CM.x, weight=merged_old$DON_WGT_KG.x, weight_ind=merged_old$weight_ind, ethnicity=merged_old$ethnicity, hypertension=merged_old$hypertension, diabetes=merged_old$diabetes, cod=merged_old$cod, creatine=merged_old$DON_CREAT.x, creatine_ind=merged_old$DON_HIGH_CREAT.x, hcv=merged_old$hcv, dcd=merged_old$dcd)
```

```{r}

#coding sequences (using kdpi mapping table)
merged_old$seq = ifelse((merged_old$REC_TX_PROCEDURE_TY %in% c(101, 102) & merged_old$kdri <= 0.73652249238699), 
  1, ifelse((merged_old$REC_TX_PROCEDURE_TY %in% c(101, 102) & merged_old$kdri > 0.73652249238699 & merged_old$kdri <= 0.86220561525508),
  2, ifelse((merged_old$REC_TX_PROCEDURE_TY %in% c(101, 102) & merged_old$kdri > 0.86220561525508 & merged_old$kdri < 1.48742806263682),
  3, ifelse(merged_old$REC_TX_PROCEDURE_TY == 103, 0, 4))))

#variables for input into epts function
merged_old = merged_old %>% 
  mutate(dialysis_duration = ifelse(is.na(merged_old$REC_DIAL_DT) == FALSE, (merged_old$REC_TX_DT-merged_old$REC_DIAL_DT)/365, 0),
  no_dial = ifelse(is.na(merged_old$REC_DIAL_DT), 1, 0),
  type = ifelse(merged_old$seq == 0, 'En Bloc', ifelse(merged_old$seq == 1, 'Sequence A SKT', ifelse(merged_old$seq == 2, 'Sequence B SKT', ifelse(merged_old$seq == 3, 'Sequence C SKT', 'Sequence D SKT')))),
  rec_diabetes = ifelse(merged_old$CAN_DIAB_TY %in% c(1, 998), 0, 1),
  rec_htn = ifelse(merged_old$CAN_DRUG_TREAT_HYPERTEN == 'Y', 1, 0),
  DON_CAD_DON_COD.x = ifelse(is.na(merged_old$DON_CAD_DON_COD.x), "997", merged_old$DON_CAD_DON_COD.x),
  enbloc_under1 = ifelse((merged_old$enbloc == 1) & (merged_old$DON_AGE.x < 1), 1, 0),
  enbloc_over1 = ifelse((merged_old$enbloc == 1) & (merged_old$DON_AGE.x >= 1), 1, 0))

save(merged_old, file = "prepolicy_cohort.Rdata")
```


